apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-basic-169681224
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/stov7fl0-tenant/test-app-169681224/python-basic-169681224@sha256:ea706010c7fedb372472331aa00d2e0deae336c58ea2cd41131eac4692737317
        name: my-python
        resources: {}
status: {}
